variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - test
    - package
    - deploy

cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  tags:
    - shared 

  script: 
    - echo "Maven compile started"
    - "pwd"
    - "mvn compile -f services/backend/fis"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

test_job:
  stage: test
  tags:
    - shared 

  script: 
    - echo "Maven test started"
    - "mvn test -f services/backend/fis"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  

package_job:
  stage: package
  tags:
    - shared 

  script: 
    - echo "Maven packaging started"
    - "mvn package -f services/backend/fis"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  


Deploy_job:
  stage: deploy
  tags:
    - shared 

  script: 
    - echo "Maven deploy started"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  
