variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - test
    - package
    - deploy

cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  tags:
    - shared 
  script: 
    - echo "Test Maven compile started"
    - "mvn compile"

test_job:
  stage: test
  tags:
    - shared 
  script: 
    - echo "Test Maven test started"
    - "mvn test"

package_job:
  stage: package
  tags:
    - shared 
  script: 
    - echo "Test Maven packaging started"
    - "mvn package"

Deploy_job:
  stage: deploy
  tags:
    - shared 
  script: 
    - echo "Test Maven deploy started"
